server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-dev-environment-at-least-256-bits-long!!}

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  autoconfigure:
    exclude:
      - org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/users/**, /api/v1/auth/**, /api/v1/admin/**

            - id: transaction-service
              uri: ${TRANSACTION_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/transactions/**, /api/v1/wallets/{walletId}/transactions/**, /api/v1/categories/**

            - id: wallet-service
              uri: ${WALLET_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/wallets/**

            - id: analytics-service
              uri: ${ANALYTICS_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api/v1/analytics/**


cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
