apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: personalfinance
data:
  SERVER_PORT: "8083"
  DB_URL: jdbc:postgresql://__RDS_ENDPOINT__:5432/transactiondb
  RABBITMQ_HOST: __MQ_ENDPOINT__
  RABBITMQ_PORT: "5671"
  JPA_DDL_AUTO: validate
  SPRING_RABBITMQ_SSL_ENABLED: "true"
