apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service-config
  namespace: personalfinance
data:
  SERVER_PORT: "8082"
  DB_URL: jdbc:postgresql://postgres.personalfinance.svc.cluster.local:5432/walletdb
  RABBITMQ_HOST: rabbitmq.personalfinance.svc.cluster.local
  RABBITMQ_PORT: "5672"
  JPA_DDL_AUTO: update

