# ─── ClusterSecretStore ────────────────────────────────────────────────────────
# Connects External Secrets Operator to AWS Secrets Manager.
# The ESO service account is already annotated with an IRSA role by Terraform.
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1 # must match your terraform aws_region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

