apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: personal-finance
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: davukx/finance-api-gateway:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-service-config
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: rabbitmq-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
