apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: personal-finance
  labels:
    app: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: davukx/finance-wallet-service:1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: wallet-service-config
            - secretRef:
                name: db-secrets
            - secretRef:
                name: rabbitmq-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
